// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz1iZ1m6WixMOtES69xtdEoKkdH66CAmo',
    appId: '1:424628033974:web:bbd56ccf4bdde5b4804917',
    messagingSenderId: '424628033974',
    projectId: 'chamada-automatizada',
    authDomain: 'chamada-automatizada.firebaseapp.com',
    storageBucket: 'chamada-automatizada.firebasestorage.app',
    measurementId: 'G-W6X37V527M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnMJkJ8fSLKO7jmbLzTI4g1M40WGIDuBA',
    appId: '1:424628033974:android:91ac354dde4c51f5804917',
    messagingSenderId: '424628033974',
    projectId: 'chamada-automatizada',
    storageBucket: 'chamada-automatizada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqOVNHYmz3OBFf0iVWCKKL9v5abw1F7Qk',
    appId: '1:424628033974:ios:e38ce1c59b73062e804917',
    messagingSenderId: '424628033974',
    projectId: 'chamada-automatizada',
    storageBucket: 'chamada-automatizada.firebasestorage.app',
    iosBundleId: 'com.example.chamadaAutomatizadaN10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqOVNHYmz3OBFf0iVWCKKL9v5abw1F7Qk',
    appId: '1:424628033974:ios:e38ce1c59b73062e804917',
    messagingSenderId: '424628033974',
    projectId: 'chamada-automatizada',
    storageBucket: 'chamada-automatizada.firebasestorage.app',
    iosBundleId: 'com.example.chamadaAutomatizadaN10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz1iZ1m6WixMOtES69xtdEoKkdH66CAmo',
    appId: '1:424628033974:web:de9e25897e6bbd41804917',
    messagingSenderId: '424628033974',
    projectId: 'chamada-automatizada',
    authDomain: 'chamada-automatizada.firebaseapp.com',
    storageBucket: 'chamada-automatizada.firebasestorage.app',
    measurementId: 'G-7ZJJNXMR5Q',
  );
}
